# tellme — development tasks
#
# Build / test conventions for the tellme CLI (round 001 — narrow foundation).
# See specs/truth/techstack.md and the plan package research.md (Decisions 4 & 7).

VERSION ?= dev

# ---- Hermetic Go-toolchain environment (ADR 0012; issue #96) -----------------
# Every recipe — and every descendant process a recipe spawns (e.g. the E2E
# harness's `go build` behind `make test`, the witness behind `verify-no-network`)
# — launches the Go toolchain through this boundary, so a persisted (`go env -w`)
# or exported Go setting cannot redden a target for reasons unrelated to the tree.
#
# The set is CRITERION-DERIVED (ADR 0012 D2): NEUTRALISE the ambient build
# context — whatever changes WHAT the toolchain builds or WHICH toolchain builds
# it; PRESERVE the plumbing — whatever only lets that build happen.
#
# NEUTRALISE:
#   * GOENV=off is load-bearing — Go falls back to the env *file* for a variable
#     that is unset OR empty, so unsetting GOFLAGS does NOT neutralise a persisted
#     `go env -w GOFLAGS=-mod=vendor` (round-042 F-2 / ADR 0011 D5);
#   * GOWORK=off — a stray go.work must not redirect the build;
#   * GOFLAGS/GO111MODULE/GOEXPERIMENT unset — module mode + build flags;
#   * GOTOOLCHAIN/GOFIPS140/GODEBUG unset — toolchain selection, build-mode
#     switch, runtime defaults (an exported GOTOOLCHAIN pin selects a different
#     toolchain: `GOTOOLCHAIN=go1.99.9 make vet` is exit 2 without this);
#   * the target triple — GOOS/GOARCH AND the micro-architecture family
#     (GOARM/GOARM64/GOAMD64/GO386/GOMIPS/GOMIPS64/GOPPC64/GORISCV64/GOWASM) —
#     unset (host-native; "host-native" for an unset GOOS/GOARCH covers the
#     OS/arch PAIR only, not the micro-arch level).
# PRESERVE (untouched): PATH/HOME/GOPATH/GOMODCACHE/GOCACHE (the warm module
# cache), and GOPROXY/GOSUMDB/GOPRIVATE/GONOSUMDB/GOINSECURE (a cold-cache or
# proxied build still resolves).
# CGO_ENABLED is preserved from the caller (neither set nor unset — NOT globally
# pinned); a recipe's INLINE per-target assignment still wins for that recipe
# (e.g. verify-cross-compile's `CGO_ENABLED=0 GOOS=… GOARCH=… go build`).
# SCOPE: recipes and their descendants only — parse-time `$(shell …)`/`$(eval …)`
# and make command-line variables are OUTSIDE this boundary (keep `go` out of
# `$(shell …)`); an already-exported name is overridden by a command-line
# assignment (`make GOENV=<file> …` — the escape hatch).
# Defence-in-depth for a gate run DIRECTLY (bypassing `make`): tools/arch's own
# `childEnv` filter (ADR 0011 D5) keeps that gate's VERDICT hermetic. The two
# sites neutralise by different mechanisms (here: disable the env file + unset;
# there: re-set explicit values), so their invariant is COVERAGE — every name
# below is re-set by `childEnv`, or recorded as a non-covered class (ADR 0012 R4) — and
# NOT set-equality (ADR 0012 D6).
export GOENV := off
export GOWORK := off
unexport GOFLAGS GO111MODULE GOEXPERIMENT GOTOOLCHAIN GOFIPS140 GODEBUG
unexport GOOS GOARCH GOARM GOARM64 GOAMD64 GO386 GOMIPS GOMIPS64 GOPPC64 GORISCV64 GOWASM
# -----------------------------------------------------------------------------

GOLANGCI := $(shell command -v golangci-lint 2>/dev/null)
GOIMPORTS := $(shell command -v goimports 2>/dev/null)
GOVULNCHECK := $(shell command -v govulncheck 2>/dev/null)

# ---- Domain model (modelith; ADR 0030; round 060) ----------------------------
# The canonical domain model lives at docs/domain-model/*.modelith.yaml (source);
# the *.modelith.md is GENERATED by modelith and never hand-edited. modelith is a
# DEV-TOOL BINARY (like golangci-lint/govulncheck above) — NOT a Go
# module dependency; go.mod/go.sum stay unchanged.
#
# INSTALL (single-sourced in docs/domain-model/README.md; quoted verbatim here).
# The fork declares the UPSTREAM module path (github.com/stacklok/modelith), so it
# is NOT installable via `go install github.com/gosharplite/modelith/...@<ref>` at
# ANY ref (the query form is rejected outright; the pseudo-version form fails with
# "module declares its path as: github.com/stacklok/modelith"). The working route
# is a local clone of the fork, checked out at an immutable commit, built locally
# (a local module build is unaffected by the declared-path mismatch):
#   git clone https://github.com/gosharplite/modelith && cd modelith && \
#     git checkout b4153541cee8 && go install ./cmd/modelith
# Provenance of the pinned build: github.com/stacklok/modelith
# v0.0.0-20260815121344-b4153541cee8 (commit b4153541cee8, vcs.modified=false).
# The drift gate (modelith-check) is a zero-tolerance member of `verify`: drift
# fails, and an ABSENT binary fails (naming the install route) — it never skips.
MODELITH := $(shell command -v modelith 2>/dev/null)
MODELITH_PIN := b4153541cee8
MODELITH_INSTALL := git clone https://github.com/gosharplite/modelith && cd modelith && git checkout $(MODELITH_PIN) && go install ./cmd/modelith
# The enumeration is a property of the TREE (TD-060-2), not a hand-maintained
# list: every docs/domain-model/*.modelith.yaml is covered, and an empty set is an
# explicit failure (never a vacuous green).
MODELITH_MODELS := $(wildcard docs/domain-model/*.modelith.yaml)
# The CODE model (the one with Go-type correspondence) — the only model the
# advisory drift check operates on; the quality/environment models are not
# code-backed (reference: MODELITH_CODE_MODEL).
MODELITH_CODE_MODEL := docs/domain-model/tellme.modelith.yaml

.PHONY: help build fmt vet tidy lint vulncheck test test-race test-fast check check-full verify verify-no-test-sleep verify-no-network verify-fmt verify-adr-index verify-cross-compile verify-mcp-sdk-confinement verify-architecture verify-architecture-update modelith-lint modelith-render modelith-check modelith-drift

help:
	@echo "tellme development tasks:"
	@echo "  make build                - Build ./cmd/tellme with -X main.version=\$$(VERSION)"
	@echo "  make fmt                  - go fmt ./..."
	@echo "  make vet                  - go vet ./..."
	@echo "  make lint                 - run golangci-lint ./... (resolved from PATH; errcheck via .golangci.yml)"
	@echo "  make vulncheck            - run govulncheck ./... (resolved from PATH)"
	@echo "  make tidy                 - go mod tidy"
	@echo "  make test                 - go test ./..."
	@echo "  make test-race            - race detector, package-by-package (NOT a verify member; ADR 0042)"
	@echo "  make test-fast            - run a SUBSET of the E2E contract (godog.paths; NOT the gate; ADR 0024)"
	@echo "  make check                - verify + test (the whole gate; ADR 0042)"
	@echo "  make check-full           - check + test-race (pre-push; ADR 0042)"
	@echo "  make verify-no-test-sleep - forbid time.Sleep for synchronization in *_test.go (ADR-036 parity)"
	@echo "  make verify-no-network    - build-graph capability guard: no net/net/http in ./cmd/tellme closure"
	@echo "  make verify-fmt           - gofmt -l: fail if any Go file is not gofmt-clean (ADR 0042)"
	@echo "  make verify-adr-index     - every docs/decisions/ ADR is indexed once (ADR 0042)"
	@echo "  make verify-cross-compile - build + vet the module for every supported POSIX target (linux/darwin, amd64/arm64)"
	@echo "  make verify-mcp-sdk-confinement - verify the MCP Go SDK is imported only under internal/infrastructure/mcp/"
	@echo "  make verify-architecture  - layer-discipline gate: import-direction over the pinned layer ranking (ADR 0011)"
	@echo "  make verify-architecture-update - regenerate tools/arch/baseline.txt from the gate's own output"
	@echo "  make modelith-lint        - validate docs/domain-model/*.modelith.yaml (modelith; ADR 0030)"
	@echo "  make modelith-render      - regenerate docs/domain-model/*.modelith.md from the YAML (never hand-edit)"
	@echo "  make modelith-check       - drift gate: fail if a committed *.modelith.md is stale (or modelith is absent)"
	@echo "  make modelith-drift       - ADVISORY (not a verify member): a modeled entity with no code anchor"
	@echo "  make verify               - aggregate: verify-no-test-sleep + verify-no-network + verify-fmt + verify-adr-index + vet + verify-cross-compile + verify-mcp-sdk-confinement + verify-architecture + modelith-check + lint + vulncheck"

# NOTE: `VERSION ?= dev` is the local/release default ONLY.
# The E2E harness must build explicitly with the sentinel
# (go build -ldflags "-X main.version=0.0.0-harness"), never via `make build`,
# so a missed injection cannot pass against the `dev` default.
build:
	go build -ldflags "-X main.version=$(VERSION)" -o tellme ./cmd/tellme

fmt:
	go fmt ./...

vet:
	@if find . -name '*.go' -not -path './.git/*' -not -path './vendor/*' | grep -q .; then \
		go vet ./...; \
	else \
		echo "  (skip) no Go packages to vet yet"; \
	fi

tidy:
	go mod tidy

lint:
ifeq ($(GOLANGCI),)
	@echo "golangci-lint not found; install: go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@latest" >&2
	@exit 1
else
	$(GOLANGCI) run ./...
endif

vulncheck:
ifeq ($(GOVULNCHECK),)
	@echo "govulncheck not found; install: go install golang.org/x/vuln/cmd/govulncheck@latest" >&2
	@exit 1
else
	$(GOVULNCHECK) ./...
endif

test: verify-mcp-sdk-confinement
	go test ./...

# test-race — the race detector, package-by-package (AI-SAFE: a per-package loop,
# not one `go test -race ./...`, so a single slow/contended package cannot time
# the whole run out). NOT a `make verify` member (race is expensive); run it on
# demand — a pre-push / closeout check. Scope defaults to the whole module; override
# with RACE_PKGS. The race detector catches data races in tellme's own process —
# the UI coordinator (mutexed writer + spinner admit goroutine), the telemetry
# sampler — which the subprocess-based E2E contract cannot instrument. Run it on
# demand (a pre-push / closeout check; ADR 0042 RF-042-1 defers a `check-full`
# aggregate).
RACE_PKGS ?= ./...
test-race:
	@echo "test-race: race detector over $(RACE_PKGS) (package-by-package) ..."
	@for pkg in $$(go list $(RACE_PKGS)); do \
		echo "  race $$pkg"; \
		go test -race -count=1 -timeout 300s $$pkg || exit 1; \
	done
	@echo "  ✓ no data races detected"

# check / check-full — the convenience aggregates (ADR 0042; resolves RF-042-1).
# `make verify` is the static/convention aggregate and does NOT run the E2E
# contract; `make test` uses the Go cache. `check` runs BOTH so "green" is the
# whole gate, and `check-full` adds the (expensive) race detector. Both are thin
# sequencers over existing targets — no new checks, no new dependency.
check:
	@$(MAKE) verify
	@$(MAKE) test

check-full:
	@$(MAKE) check
	@$(MAKE) test-race

# test-fast — a SUBSET of the executable contract for a fast inner loop.
#
# THIS IS NOT THE GATE. The gate is `make test` (== `go test ./...`, run as
# `go test -count=1 ./...` at a phase gate), which always executes EVERY Example
# under specs/truth/features/cli (240 Examples, round 055 / ADR 0024 D2, FR-002):
# a subset SELECTS for convenience and never EXCLUDES from the gate.
#
# The never-the-gate invariant is enforced in the HARNESS (tests/e2e/suite_test.go
# `guardSelection`), which resolves the selection to the set of `.feature` files
# it contains and refuses one that resolves back to the whole contract — so BOTH
# entry points (`make test-fast` and a hand-typed `go test -args -godog.paths`)
# obey it (round-055 review B-055-1); the selected run is banner-marked there.
# This recipe only assembles the selection and fails loud on an empty list or a
# missing module.
#
# Selector: godog.paths only (godog v0.16.0 has no name filter, and tags would
# edit specs/truth/features/** — a truth-owner change; see ADR 0024 RF-055-1).
# Caveats (ADR 0024 D3, review R-055-x): only `paths` is registered — the other
# `godog.*` flags are undefined (the concurrency seam is TELL_ME_E2E_CONCURRENCY,
# not `-godog.concurrency`); and `-args` is application-wide, so this is a
# tests/e2e-only invocation.
#
# Default selection: the non-chat modules (43 of 240 Examples — `chat` alone is
# 197, so a chat-only subset would not be fast). Override with E2E_FAST_MODULES.
#
# Round 055 (ADR 0024 D3).
E2E_FAST_MODULES ?= configuration history workspace usage diagnostics
# E2E_FEATURES_ROOT is repo-relative (used for the module existence check);
# E2E_FEATURES_REL is what godog resolves, relative to tests/e2e (its CWD).
E2E_FEATURES_ROOT := specs/truth/features/cli
E2E_FEATURES_REL := ../../specs/truth/features/cli

test-fast:
	@root="$(E2E_FEATURES_ROOT)"; \
	rel="$(E2E_FEATURES_REL)"; \
	if [ -z "$$(echo $(E2E_FAST_MODULES))" ]; then \
		echo "❌ test-fast: no modules selected (E2E_FAST_MODULES is empty)."; exit 1; \
	fi; \
	rootp="$$(cd "$$root" && pwd -P)"; \
	paths=""; \
	for m in $(E2E_FAST_MODULES); do \
		if [ ! -d "$$root/$$m" ]; then echo "❌ test-fast: no such module '$$m' under $$root"; exit 1; fi; \
		if [ "$$(cd "$$root/$$m" && pwd -P)" = "$$rootp" ]; then \
			echo "❌ test-fast refuses to run: module '$$m' resolves to the whole contract ($$root)."; \
			echo "   That is the gate — run: make test"; exit 1; \
		fi; \
		case ",$$paths," in *,$$rel/$$m,*) ;; *) paths="$$paths$${paths:+,}$$rel/$$m" ;; esac; \
	done; \
	echo "════════════════════════════════════════════════════════════════"; \
	echo "  SUBSET — NOT THE GATE"; \
	echo "  selected: $$paths"; \
	echo "  the gate: make test   (all Examples under $$root)"; \
	echo "════════════════════════════════════════════════════════════════"; \
	go test -count=1 ./tests/e2e/ -args -godog.paths="$$paths"

# Determinism gate (ADR-036 parity): no time.Sleep for synchronization in tests.
verify-no-test-sleep:
	@echo "verify-no-test-sleep: scanning *_test.go for time.Sleep synchronization ..."
	@if grep -rn 'time\.Sleep(' --include='*_test.go' . ; then \
		echo "❌ time.Sleep found in a test file; use deterministic primitives (ready channels / poll loops)."; \
		exit 1; \
	fi
	@echo "  ✓ no time.Sleep in test files"

# Build-graph capability guard (research.md Decision 5, backstop witness).
# Single definition: delegates to the Go guard in tests/e2e (harness), so the
# Makefile and the scenario step never drift (previously two diverging copies).
verify-no-network:
	@echo "verify-no-network: offline-path witness (recording sink + differential) ..."
	@if ! go list ./cmd/tellme >/dev/null 2>&1; then \
		echo "  (skip) ./cmd/tellme package not present yet"; exit 0; \
	fi
	@go test -count=1 -run TestOfflinePathsDoNotContactProvider ./tests/e2e/
	@echo "  ✓ offline paths (--version, -d, prompt-less boot) make no provider request"

# Cross-compile gate (round 020): compile + vet the module for every supported
# target, so build-tagged, OS-specific code (e.g.
# internal/infrastructure/telemetry/system_metrics_{linux,darwin}.go) can never
# silently fail to compile for a platform we ship. Host-independent: it verifies
# the whole matrix regardless of the host GOOS/GOARCH — round 019's darwin
# sampler shipped broken because `make verify` only builds the host target.
# CGO_ENABLED=0 pins pure-Go cross-compilation so an ambient `CGO_ENABLED=1`
# (a host shell/CI export) can never make a cross build fail by invoking the
# host C compiler against target assembly/headers (PR #46 review — TD1).
CROSS_TARGETS := linux/amd64 linux/arm64 darwin/amd64 darwin/arm64
verify-cross-compile:
	@echo "verify-cross-compile: build + vet for $(CROSS_TARGETS) ..."
	@for target in $(CROSS_TARGETS); do os=$${target%/*}; arch=$${target#*/}; echo "  cross-build $$os/$$arch"; CGO_ENABLED=0 GOOS=$$os GOARCH=$$arch go build ./... || { echo "❌ go build failed for $$os/$$arch"; exit 1; }; CGO_ENABLED=0 GOOS=$$os GOARCH=$$arch go vet ./... || { echo "❌ go vet failed for $$os/$$arch"; exit 1; }; done
	@echo "  ✓ cross-compiles and vets for all supported targets"

# MCP SDK confinement gate (round 032, ADR-067 parity): the official MCP Go SDK
# may be imported ONLY under internal/infrastructure/mcp/ (production AND
# _test.go files, including the SDK-built fake in mcptest/). Every other layer
# consumes the tools.MCPClient domain port. Mirrors the reference's
# verify-mcp-sdk-confinement.
verify-mcp-sdk-confinement:
	@echo "verify-mcp-sdk-confinement: MCP Go SDK imports confined to internal/infrastructure/mcp/ ..."
	@VIOLATIONS="$$( grep -rn 'github.com/modelcontextprotocol/go-sdk' --include='*.go' --exclude-dir=vendor --exclude-dir=.git . | grep -v '^\./internal/infrastructure/mcp/' )"; \
	if [ -n "$$VIOLATIONS" ]; then \
		echo ""; \
		echo "❌ verification violation: MCP Go SDK imported outside internal/infrastructure/mcp/."; \
		echo "   The SDK is confined to the MCP adapter; consume tools.MCPClient instead."; \
		echo ""; \
		echo "$$VIOLATIONS"; \
		exit 1; \
	fi
	@echo "  ✓ MCP Go SDK imports confined to internal/infrastructure/mcp/"

# Format gate (ADR 0042): `make fmt` MUTATES; this CHECKS. Two layers: `gofmt -l`
# (the toolchain's own formatter, always) and `goimports -l` (gofmt + import
# grouping — stdlib / external groups; resolved from PATH, a documented prereq
# like golangci-lint/modelith). Either being non-empty fails — so formatting AND
# import-ordering drift are caught in the pipeline, not only at closeout. Fast,
# hermetic once the tools resolve. gofumpt is deliberately NOT adopted (a stricter
# style with no reference parity — ADR 0042 RF-042-2).
verify-fmt:
	@echo "verify-fmt: gofmt -l + goimports -l (no unformatted / ungrouped Go files) ..."
	@out=$$(gofmt -l . 2>/dev/null); \
	if [ -n "$$out" ]; then \
		echo ""; echo "❌ gofmt would reformat:"; echo "$$out"; echo ""; \
		echo "Fix: run 'make fmt'."; exit 1; \
	fi
ifeq ($(GOIMPORTS),)
	@echo "verify-fmt: goimports not found; install: go install golang.org/x/tools/cmd/goimports@latest" >&2
	@exit 1
else
	@out=$$($(GOIMPORTS) -l . 2>/dev/null); \
	if [ -n "$$out" ]; then \
		echo ""; echo "❌ goimports would reformat (import grouping):"; echo "$$out"; echo ""; \
		echo "Fix: run 'goimports -w .'."; exit 1; \
	fi
endif
	@echo "  ✓ all Go files gofmt- and goimports-clean"

# ADR-index gate (ADR 0042): every ADR file on disk is listed in
# docs/decisions/README.md and no ADR number is claimed twice. The index is
# hand-maintained; this makes its consistency mechanical (fast, hermetic).
verify-adr-index:
	@echo "verify-adr-index: every ADR is indexed and numbered once ..."
	@fail=0; \
	for f in docs/decisions/[0-9]*.md; do \
		[ -e "$$f" ] || continue; \
		b=$$(basename "$$f"); \
		grep -qF "$$b" docs/decisions/README.md || { echo "  ❌ $$b missing from docs/decisions/README.md"; fail=1; }; \
	done; \
	dupes=$$(grep -h '^# ADR [0-9]' docs/decisions/[0-9]*.md 2>/dev/null | sed -E 's/^# ADR ([0-9]+).*/\1/' | sort -n | uniq -d); \
	if [ -n "$$dupes" ]; then echo "  ❌ duplicate ADR number(s): $$dupes"; fail=1; fi; \
	if [ "$$fail" -ne 0 ]; then echo "  → fix docs/decisions/README.md (add the row / renumber)"; exit 1; fi
	@echo "  ✓ ADR index consistent (all files indexed, numbers unique)"

# Layer-discipline gate (round 042, ADR 0011): an import-direction check over the
# pinned layer ranking (domain -> config/home -> app -> infrastructure -> agent ->
# ui -> cli; cmd/tests/tools exempt), evaluated as the union over CROSS_TARGETS so
# an OS-gated illegal import cannot hide. The committed tools/arch/baseline.txt is
# a fail-on-stale ratchet: a new violation fails, and a stale baseline line fails.
verify-architecture:
	@echo "verify-architecture: layer-discipline gate (import-direction over the pinned ranking; ADR 0011) ..."
	@go vet -tags=arch ./tools/arch
ifeq ($(GOLANGCI),)
	@echo "  (skip) golangci-lint not found; the tagged guard is not lint-checked (go vet still ran)"
else
	@$(GOLANGCI) run --build-tags=arch ./tools/arch/...
endif
	@go test -count=1 -tags=arch -run TestVerifyRealArchitecture ./tools/arch
	@echo "  ✓ no layer violation beyond the baseline; no import cycles"

# Regenerate the committed baseline from the gate's own output (never hand-edit).
# Not part of `verify` — the ratchet must not rewrite its own baseline.
verify-architecture-update:
	@echo "verify-architecture-update: regenerating tools/arch/baseline.txt from the gate ..."
	@go test -count=1 -tags=arch -run TestVerifyRealArchitecture ./tools/arch -args -update-baseline

# ---- Domain model targets (ADR 0030; round 060) ------------------------------
# The YAML is the single source; the .md is generated. `modelith-check` is the
# zero-tolerance drift gate — wired into `verify` (below). An ABSENT modelith is
# a hard failure naming the install command (never a silent skip).
modelith-lint:
ifeq ($(MODELITH),)
	@echo "modelith-lint: modelith not found on PATH. Install it with:"; echo "  $(MODELITH_INSTALL)"; exit 1
else
	@test -n "$(MODELITH_MODELS)" || { echo "modelith-lint: no docs/domain-model/*.modelith.yaml found" >&2; exit 1; }
	@for m in $(MODELITH_MODELS); do echo "  modelith-lint $$m"; $(MODELITH) lint $$m || exit 1; done
endif

modelith-render:
ifeq ($(MODELITH),)
	@echo "modelith-render: modelith not found on PATH. Install it with:"; echo "  $(MODELITH_INSTALL)"; exit 1
else
	@test -n "$(MODELITH_MODELS)" || { echo "modelith-render: no docs/domain-model/*.modelith.yaml found" >&2; exit 1; }
	@for m in $(MODELITH_MODELS); do echo "  modelith-render $$m"; $(MODELITH) render $$m || exit 1; done
endif

modelith-check:
ifeq ($(MODELITH),)
	@echo "modelith-check: modelith not found on PATH. Install it with:"; echo "  $(MODELITH_INSTALL)"; exit 1
else
	@test -n "$(MODELITH_MODELS)" || { echo "modelith-check: no docs/domain-model/*.modelith.yaml found" >&2; exit 1; }
	@for m in $(MODELITH_MODELS); do echo "  modelith-check $$m"; $(MODELITH) render --check $$m || exit 1; done
	@echo "  ✓ committed *.modelith.md matches the YAML source (no drift)"
endif

# modelith-drift — ADVISORY, never fails, NOT a `verify` member. Surfaces a
# modeled entity whose concept has vanished from the code (a stale model entry).
# The domain model is load-bearing: a round that changes MODELLED behaviour
# updates docs/domain-model/** in the same PR — this target is the advisory aid
# (see docs/domain-model/README.md -> Drift guard; ADR 0041). Scope: the CODE
# model only. POSIX-only (grep/awk/sed).
modelith-drift:
	@scripts/modelith-drift.sh $(MODELITH_CODE_MODEL)

# `vet` runs before `verify-cross-compile` for fail-fast on host-local errors;
# `verify-cross-compile` then re-covers the host target as part of the matrix.
# verify-fmt / verify-adr-index are the ADR-0042 additions (format + ADR-index).
verify: verify-no-test-sleep verify-no-network verify-fmt verify-adr-index vet verify-cross-compile verify-mcp-sdk-confinement verify-architecture modelith-check lint vulncheck
	@echo "verify: OK"
